
#Name of WorkFlow
name: Continuous Integration and Deployment
#Run on every commit to 'lab1' branch
on:
  push:  
    branches: [ lab1 ]
#Build, Create Artifacts in GitHub & Deploy 
jobs:
#region 'JOB 1 : BUILD'
  build:
    runs-on: ubuntu-latest    
    env:
      CI: "" 
      DOTNET_VERSION: '5.0.x'  
      PUBLISH_PATH: './runner/output'

    steps:
    - name: Step 1 - CHECK Out Code       
      uses: actions/checkout@v2
    - name: Step 2 - SETUP .NET 4.6.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Step 3 - RESTORE the Dependencies 
      run: dotnet restore
    - name: Step 4 - BUILD the API  
      run: dotnet build ./*.sln --configuration Release --no-restore
#Create the Publish files & place in a folder in the Runner      
    - name: Step 5 - PUBLISH the project
      run: dotnet publish ./TheCoreAPI/TheCoreAPI.csproj -c Release -o ${{ env.PUBLISH_PATH }}
#Upload the publish Artifacts from Runner Folder to GitHub Drop, so that w can use for deployment
    - name: Step 6 - UPLOAD ARTIFACTS to gitHub
      uses: actions/upload-artifact@v2
      with: 
        name: drop 
        path: ${{ env.PUBLISH_PATH }}
#endregion
#region 'JOB 2 : DEPLOY'
  deploy:
    needs: build      #dependency, first build must run
    runs-on: ubuntu-latest    
    env:
      CD: "" 
    
    steps:
    - name: Step 1 - DOWNLOAD ARTIFACTS from gitHub to this runner    
      uses: actions/download-artifact@v2
      with: 
        name: drop 
        path: './staging'
    #-name: Step 2 - Deploy the downloaded Artifacts in Azure, etc.
    
#endregion