
name: Continuous Integration and Deployment
on:
  push:  
    #branches: [ lab3 ]
    paths:
      - userguide.md  #workflow triggers if userguide is modified
jobs:
#region 'JOB 1 : BUILD'
  build:
    runs-on: ubuntu-latest    
    env:      
      DOTNET_VERSION: '5.0.x'  
      PUBLISH_PATH: './runner/output'
    steps:
    - name: Step 1 - CHECK Out Code       
      uses: actions/checkout@v2
    - name: Step 2 - SETUP .NET 4.6.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Step 3 - RESTORE the Dependencies 
      run: dotnet restore
    - name: Step 4 - BUILD the API  
      run: dotnet build ./*.sln --configuration Release --no-restore   
    - name: Step 5 - PUBLISH the project
      run: dotnet publish ./TheCoreAPI/TheCoreAPI.csproj -c Release -o ${{ env.PUBLISH_PATH }}      
    - name: Step 6 - UPLOAD ARTIFACTS to gitHub
      uses: actions/upload-artifact@v2
      with: 
        name: drop 
        path: ${{ env.PUBLISH_PATH }}    #Path from where to grab the Artifacts   
#endregion

#region 'JOB 2 : RELEASE 
  deploy:
    needs: build      #dependency, first build must run
    runs-on: ubuntu-latest            
    steps:    
    - name: Step 1 -CREATE RELEASE      
      uses: actions/create-release@v1
      env:      
        GITHUB_TOKEN: ${{ secrets.github_token }} 
      with:
        tag_name: ${{ github.run_number }}  
        release_name: Release ${{ github.run_number }}
        body: New release for ${{ github.sha }}. Release notes LINK can be put here .
        draft: false
        prerelease: false    
  #endregion
        
  #region 'JOB 3 : DOCUMENTATION'
  documentation:
    needs: build      #dependency, first build must run
    runs-on: ubuntu-latest            
    steps:  
    - name: Step 1 - CHECKOUT CODE
      uses: actions/checkout@v2
    - name: Step 2 - CREATE FOLDER
      uses: mkdir docs
    - name: Step 3 - CONVERT MD TO HTML
      uses: docker://pandoc/core:2.9
      with: 
        args: userguide.md -t html -o docs/index.html 
    - name: Step 3 - DEPLOY PAGES
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        folder: docs
        branch: gh-pages
  # #endregion